---
- hosts: test-server
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Stop existing container (if running)
      command: sudo docker ps -q --filter "publish=8081" | xargs -r sudo docker stop
      ignore_errors: yes

    - name: Remove old container
      command: sudo docker ps -aq --filter "publish=8081" | xargs -r sudo docker rm
      ignore_errors: yes

    - name: Deploy InsureMe application
      command: sudo docker run -itd --name insureme-container -p 8081:8081 abhi144k/insureme:1.0
